apiVersion: apps/v1
kind: Deployment
metadata:
  name: ketei
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ketei
  template:
    metadata:
      labels:
        app: ketei
    spec:
      containers:
      - image: okteto.dev/ketei:latest
        name: ketei
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "07e377ac-9b90-442c-9e8d-26a83149ddbf"
        - name: Vless_Path
          value: "/tudeiopA"
        - name: Vmess_UUID
          value: "07e377ac-9b90-442c-9e8d-26a83149ddbf"
        - name: Vmess_Path
          value: "/uedrtgfc"
        - name: Share_Path
          value: "/share233"
